import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [text, setText] = useState("Timezones");
  const [size, setSize] = useState(14);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Text-Svg-Rotate!</h1>
        <label>Text</label>
        <input
          type="text"
          onChange={(e) => setText(e.target.value)}
          value={text}
        />
        <label>Size</label>
        <input
          type="number"
          min="10"
          max="99"
          onChange={(e) => setSize(parseInt(e.target.value))}
          value={size}
        />
        <label>url</label>
        <input
          style={{ width: "600px", height: 40 }}
          type="textarea"
          disabled
          value={`${
            process.env.NEXT_PUBLIC_VERCEL_URL || "http://localhost:3000"
          }/api/${text || "Timezones"}?color=black&size=${size || 14}`}
          width="150px"
        />
        <label>MD image</label>
        <input
          style={{ width: "600px", height: 40 }}
          type="textarea"
          disabled
          value={
            `${
              process.env.NEXT_PUBLIC_VERCEL_URL || "![](http://localhost:3000"
            }/api/${text}?color=black&size=${size || 14}#gh-light-mode-only)` +
            " " +
            `${
              process.env.NEXT_PUBLIC_VERCEL_URL || "![](http://localhost:3000"
            }/api/${text}?color=white&size=${size || 14}#gh-dark-mode-only)`
          }
          width="150px"
        />

        <label>Preview</label>
        <iframe
          src={`/api/${text.trim()}?color=black&size=${size}`}
          width={size * 1.3}
          height={size * 0.6 * text.length}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/agustif/rotate-svg-text"
          target="_blank"
          // style={{textDecoratiomn="underline"}}
          rel="noopener noreferrer"
        >
          Made by @agustif
        </a>
      </footer>
    </div>
  );
};

export default Home;
